
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./.env

    command: node server.js

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  admin:
    build:
      context: ./admin
    container_name: admin
    ports:
      - "4000:80"
    depends_on:
      - backend



