apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: /nagarajutl/food-delivery-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: tomato-secrets
                  key: MONGO_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: tomato-secrets
                  key: JWT_SECRET
