apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/nagarajutl/food-delivery-frontend:sha-062304f
          ports:
            - containerPort: 80
      imagePullSecrets:
            - name: github-container-registry
